export function callWithErrorHandling(fn: any, instance: any, info: any, args: any): any;
